---
roles:
  # Install a role from Ansible Galaxy.
  - name: mullholland.repository_epel
  - name: mullholland.docker

collections:
  # https://docs.ansible.com/ansible/latest/collections/community/docker/docker_network_module.html
  - name: community.docker
    source: https://galaxy.ansible.com
