---
- name: create user
  ansible.builtin.include_tasks:
    file: user.yml

- name: create docker network
  ansible.builtin.include_tasks:
    file: docker.yml

- name: prepare traefik
  ansible.builtin.include_tasks:
    file: traefik.yml
