---
- name: Create user
  ansible.builtin.include_tasks:
    file: user.yml

- name: Create docker network
  ansible.builtin.include_tasks:
    file: docker.yml

- name: Prepare traefik
  ansible.builtin.include_tasks:
    file: traefik.yml
