---
- name: traefik | set application facts
  ansible.builtin.set_fact:
    app_name: "traefik"
    app_image: "{{ traefik_docker_version }}"
    app_network: "{{ traefik_docker_network_name }}"
    app_base_path: "{{ traefik_docker_base_path }}"
    app_user: "{{ traefik_docker_user }}"
    app_uid: "{{ traefik_docker_uid }}"
    app_group: "{{ traefik_docker_group }}"
    app_gid: "{{ traefik_docker_gid }}"
    app_timezone: "{{ traefik_docker_timezone }}"
    app_environment_variables: "{{ traefik_docker_environment_variables }}"
    app_commands: "{{ traefik_docker_commands }}"
    app_volumes: "{{ traefik_docker_volumes }}"
    app_labels: "{{ traefik_docker_labels }}"
    app_ports: "{{ traefik_docker_ports }}"

- name: "traefik | Ensure app folders exists"
  ansible.builtin.file:
    name: '{{ app_base_path }}/{{ app_name }}/{{ item }}'
    owner: "{{ app_user }}"
    group: "{{ app_group }}"
    mode: "0770"
    state: directory
  with_items:
    - "ssl"
    - "config"

- name: "traefik | Ensure config config.yml exists"
  ansible.builtin.template:
    src: "config.yml.j2"
    dest: "{{ app_base_path }}/{{ app_name }}/config/config.yml"
    mode: "0640"
    owner: "{{ app_user }}"
    group: "{{ app_group }}"
  notify: traefik_restart
  when: traefik_docker_config and traefik_docker_config|length

- name: traefik | get docker executable path
  ansible.builtin.command:
    cmd: "which docker"
  changed_when: false
  register: traefik_docker_executable_path

- name: "traefik | create docker-compose.yml"
  ansible.builtin.template:
    src: "docker-compose.yml.j2"
    dest: "{{ app_base_path }}/{{ app_name }}/docker-compose.yml"
    mode: "0640"
    owner: "{{ app_user }}"
    group: "{{ app_group }}"
  notify: traefik_restart

- name: "traefik | Create systemd service"
  ansible.builtin.template:
    src: "systemd.service.j2"
    dest: "/etc/systemd/system/{{ app_name }}.service"
    mode: "0770"
    owner: "root"
    group: "root"
  notify:
    - traefik_systemd_reload
    - traefik_restart
