---
- name: user | Ensure group exists
  ansible.builtin.group:
    name: "{{ traefik_docker_group }}"
    gid: "{{ traefik_docker_gid }}"
    state: present

- name: user | Ensure user exists with gid
  ansible.builtin.user:
    name: "{{ traefik_docker_user }}"
    uid: "{{ traefik_docker_uid }}"
    system: "{{ traefik_docker_users_system | default(omit) }}"
    state: "present"
