---
- name: Converge
  hosts: all
  become: true
  gather_facts: true
  vars:
    traefik_docker_config:
      tls:
        options:
          modern:
            minVersion: "VersionTLS13"
            sniStrict: true

  roles:
    - role: "ansible-role-traefik_docker"
