---
- name: Verify
  hosts: all
  become: true
  gather_facts: true
  vars:
    verify:
      package: "example"
      config_file: "/opt/traefik/config/config.yml"
      config_line: '            minVersion: VersionTLS13'
      config_owner: "homelab"
      config_group: "homelab"
      config_mode: "0640"
      compose_file: "/opt/traefik/docker-compose.yml"
      compose_line: '    image: "traefik:latest"'
      compose_owner: "homelab"
      compose_group: "homelab"
      compose_mode: "0640"
      service_file: "/etc/systemd/system/traefik.service"
      service_line: 'Description=traefik service with docker compose'
      service_owner: "root"
      service_group: "root"
      service_mode: "0770"
      daemon: "traefik"

  tasks:
    - name: SmokeTests
      ansible.builtin.debug:
        msg:
          - "ansible_version => {{ansible_version}}"
          - "ansible_distribution => {{ ansible_distribution }}"
          - "ansible_distribution_major_version => {{ ansible_distribution_major_version }}"
          - "ansible_os_family  => {{ ansible_os_family}}"
          - "ansible_system  => {{ ansible_system }}"

    - name: check {{ verify.config_file }} conf file
      lineinfile:
        name: "{{ verify.config_file }}"
        line: "{{ verify.config_line }}"
        state: present
        owner: "{{ verify.config_owner }}"
        group: "{{ verify.config_group }}"
        mode: "{{ verify.config_mode }}"
      check_mode: true
      register: molecule_hcl
      failed_when: (molecule_hcl is changed) or (molecule_hcl is failed)

    - name: check {{ verify.compose_file }} conf file
      lineinfile:
        name: "{{ verify.compose_file }}"
        line: "{{ verify.compose_line }}"
        state: present
        owner: "{{ verify.compose_owner }}"
        group: "{{ verify.compose_group }}"
        mode: "{{ verify.compose_mode }}"
      check_mode: true
      register: molecule_hcl
      failed_when: (molecule_hcl is changed) or (molecule_hcl is failed)

    - name: check {{ verify.service_file }} conf file
      lineinfile:
        name: "{{ verify.service_file }}"
        line: "{{ verify.service_line }}"
        state: present
        owner: "{{ verify.service_owner }}"
        group: "{{ verify.service_group }}"
        mode: "{{ verify.service_mode }}"
      check_mode: true
      register: molecule_hcl
      failed_when: (molecule_hcl is changed) or (molecule_hcl is failed)

    - name: check {{ verify.daemon }} daemon
      service:
        name: "{{ verify.daemon }}"
        state: started
        enabled: true
      check_mode: true
      register: molecule_service
      failed_when: (molecule_service is changed) or (molecule_service is failed)
